// src/angular/StorageExampleComponent.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import { AngularSystemStorageService } from '../angular';

/**
 * Example Angular component using the storage service
 */
@Component({
  selector: 'app-storage-example',
  templateUrl: './storage-example.component.html',
  styleUrls: ['./storage-example.component.css']
})
export class StorageExampleComponent implements OnInit, OnDestroy {
  token: string | null = null;
  tokenLoading = false;
  tokenError: Error | null = null;

  itemData: any = null;
  itemError: Error | null = null;
  itemLoading = false;

  private destroy$ = new Subject<void>();

  constructor(private storageService: AngularSystemStorageService) {}

  ngOnInit(): void {
    // Initialize the service
    this.storageService.initialize('http://localhost:3000');

    // Subscribe to token changes
    this.storageService.token$
      .pipe(takeUntil(this.destroy$))
      .subscribe(token => (this.token = token));

    this.storageService.tokenLoading$
      .pipe(takeUntil(this.destroy$))
      .subscribe(loading => (this.tokenLoading = loading));

    this.storageService.tokenError$
      .pipe(takeUntil(this.destroy$))
      .subscribe(error => (this.tokenError = error));

    // Request token on init
    this.requestToken();
  }

  requestToken(): void {
    this.storageService
      .requestToken()
      .pipe(takeUntil(this.destroy$))
      .subscribe(
        response => console.log('Token received:', response),
        error => console.error('Token error:', error)
      );
  }

  getItem(id: string = 'my-item-id'): void {
    this.itemLoading = true;
    this.itemError = null;

    this.storageService
      .getItem(id)
      .pipe(takeUntil(this.destroy$))
      .subscribe(
        data => {
          this.itemData = data;
          this.itemLoading = false;
        },
        error => {
          this.itemError = error;
          this.itemLoading = false;
        }
      );
  }

  saveItem(id: string = 'my-item-id'): void {
    const dataToSave = { name: 'Test Item', value: 42 };
    this.itemLoading = true;
    this.itemError = null;

    this.storageService
      .saveItem(id, dataToSave)
      .pipe(takeUntil(this.destroy$))
      .subscribe(
        result => {
          this.itemData = result;
          this.itemLoading = false;
        },
        error => {
          this.itemError = error;
          this.itemLoading = false;
        }
      );
  }

  logout(): void {
    this.storageService.logout();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

// src/react/StorageExample.tsx
import React, { useEffect, useState } from 'react';
import { useStorageContext } from '../react';

/**
 * Example React component using the storage service
 */
export function StorageExample() {
  const { 
    token, 
    tokenLoading, 
    tokenError, 
    requestToken, 
    getItem, 
    saveItem,
    logout 
  } = useStorageContext();

  const [itemData, setItemData] = useState<any>(null);
  const [itemError, setItemError] = useState<Error | null>(null);
  const [itemLoading, setItemLoading] = useState(false);

  // Request token on mount
  useEffect(() => {
    if (!token) {
      requestToken();
    }
  }, []);

  // Fetch an item
  const handleGetItem = async () => {
    setItemLoading(true);
    setItemError(null);
    const result = await getItem('my-item-id');
    if (result.error) {
      setItemError(result.error);
    } else {
      setItemData(result.data);
    }
    setItemLoading(false);
  };

  // Save an item
  const handleSaveItem = async () => {
    const dataToSave = { name: 'Test Item', value: 42 };
    setItemLoading(true);
    setItemError(null);
    const result = await saveItem('my-item-id', dataToSave);
    if (result.error) {
      setItemError(result.error);
    } else {
      setItemData(result.data);
    }
    setItemLoading(false);
  };

  return (
    <div>
      <h1>Storage Service Example</h1>

      {/* Token Section */}
      <section>
        <h2>Authentication</h2>
        {tokenLoading && <p>Loading token...</p>}
        {tokenError && <p style={{ color: 'red' }}>Error: {tokenError.message}</p>}
        {token && <p>✓ Authenticated with token: {token.substring(0, 20)}...</p>}
        <button onClick={() => requestToken()} disabled={tokenLoading}>
          {token ? 'Refresh Token' : 'Get Token'}
        </button>
        {token && <button onClick={logout}>Logout</button>}
      </section>

      {/* Item Operations */}
      <section>
        <h2>Item Operations</h2>
        {itemLoading && <p>Loading...</p>}
        {itemError && <p style={{ color: 'red' }}>Error: {itemError.message}</p>}
        {itemData && (
          <pre>{JSON.stringify(itemData, null, 2)}</pre>
        )}
        <button onClick={handleGetItem} disabled={!token || itemLoading}>
          Get Item
        </button>
        <button onClick={handleSaveItem} disabled={!token || itemLoading}>
          Save Item
        </button>
      </section>
    </div>
  );
}
